name = "long-carrot"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }
